Traceback (most recent call last):
  File "fetch_our_lazada_product.py", line 83, in <module>
    l.remove_all_product()
  File "fetch_our_lazada_product.py", line 10, in remove_all_product
    skus = [s['SellerSku'] for s in rm_sku['Skus']]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "fetch_our_lazada_product.py", line 83, in <module>
    l.remove_all_product()
  File "fetch_our_lazada_product.py", line 10, in remove_all_product
    skus = [s['SellerSku'] for s in rm_sku['Skus']]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fetch_our_lazada_product.py", line 91, in <module>
    status='all',
  File "/home/ctdata05/ctdata/chinabrand_resource/lazada.py", line 549, in get_product
    return self._post("GetProducts", extra_param=extra_param)
  File "/home/ctdata05/ctdata/chinabrand_resource/lazada.py", line 778, in _post
    result = requests.post(url, params=parameters, data=data or {})
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fetch_our_lazada_product.py", line 91, in <module>
    status='all',
  File "/home/ctdata05/ctdata/chinabrand_resource/lazada.py", line 549, in get_product
    return self._post("GetProducts", extra_param=extra_param)
  File "/home/ctdata05/ctdata/chinabrand_resource/lazada.py", line 778, in _post
    result = requests.post(url, params=parameters, data=data or {})
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/ctdata05/.envs/ctdata/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
Traceback (most recent call last):
  File "fetch_our_lazada_product.py", line 83, in <module>
    l.remove_all_product()
  File "fetch_our_lazada_product.py", line 10, in remove_all_product
    skus = [s['SellerSku'] for s in rm_sku['Skus']]
TypeError: 'NoneType' object is not subscriptable
